language: node_js
node_js:
  - '14'
  - '16'
  - '18'
before_install:
  - curl -L https://raw.githubusercontent.com/pnpm/self-installer/master/install.js | node
install:
  - pnpm install
script:
  - pnpm test
